// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nprkhqxhvergyikusvbc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5wcmtocXhodmVyZ3lpa3VzdmJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MzQ2NzYsImV4cCI6MjA2NTUxMDY3Nn0.DGh6dh5UQpgiPG4duteeWuST0Go3tMkKAW3UCzyMobU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);